// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5HtheWr3yMMCoFXwAWsWcN
// Component: 4nZ-1b6hTn9
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as pp from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  useTrigger,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Select__Overlay from "../../Select__Overlay"; // plasmic-import: WYNBk5oeT7l/component
import Select__Option from "../../Select__Option"; // plasmic-import: vMCHMNk5Xu9/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 5HtheWr3yMMCoFXwAWsWcN/projectcss
import * as sty from "./PlasmicSelect.module.css"; // plasmic-import: 4nZ-1b6hTn9/css
import ChevronDownsvgIcon from "./icons/PlasmicIcon__ChevronDownsvg"; // plasmic-import: KOHaD46hYeu/icon
import ChevronUpsvgIcon from "./icons/PlasmicIcon__ChevronUpsvg"; // plasmic-import: JYKoVhGf7xx/icon

export const PlasmicSelect__VariantProps = new Array(
  "showPlaceholder",
  "isOpen",
  "isDisabled",
  "color"
);

export const PlasmicSelect__ArgProps = new Array(
  "selectedContent",
  "placeholder",
  "children",
  "value",
  "name"
);

const PlasmicSelectContext = React.createContext(undefined);

function PlasmicSelect__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const [isRootFocusVisibleWithin, triggerRootFocusVisibleWithinProps] =
    useTrigger("useFocusVisibleWithin", {
      isTextInput: false
    });

  const triggers = {
    focusVisibleWithin_root: isRootFocusVisibleWithin
  };

  return (
    <PlasmicSelectContext.Provider value={{ variants, args }}>
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
          [sty.root_____focusVisibleWithin]: triggers.focusVisibleWithin_root,
          [sty.root__color_clear]: hasVariant(variants, "color", "clear"),
          [sty.root__color_softBlue]: hasVariant(variants, "color", "softBlue"),
          [sty.root__color_softCyan]: hasVariant(variants, "color", "softCyan"),
          [sty.root__color_softGreen]: hasVariant(
            variants,
            "color",
            "softGreen"
          ),

          [sty.root__color_softOrange]: hasVariant(
            variants,
            "color",
            "softOrange"
          ),

          [sty.root__color_softPink]: hasVariant(variants, "color", "softPink"),
          [sty.root__color_softPurple]: hasVariant(
            variants,
            "color",
            "softPurple"
          ),

          [sty.root__color_softRed]: hasVariant(variants, "color", "softRed"),
          [sty.root__color_softYellow]: hasVariant(
            variants,
            "color",
            "softYellow"
          ),

          [sty.root__isOpen]: hasVariant(variants, "isOpen", "isOpen")
        })}
        data-plasmic-trigger-props={[triggerRootFocusVisibleWithinProps]}
      >
        <button
          data-plasmic-name={"trigger"}
          data-plasmic-override={overrides.trigger}
          className={classNames(defaultcss.button, sty.trigger, {
            [sty.trigger_____focusVisibleWithin]:
              triggers.focusVisibleWithin_root,
            [sty.trigger__color_clear]: hasVariant(variants, "color", "clear"),
            [sty.trigger__color_softBlue]: hasVariant(
              variants,
              "color",
              "softBlue"
            ),

            [sty.trigger__color_softCyan]: hasVariant(
              variants,
              "color",
              "softCyan"
            ),

            [sty.trigger__color_softGray]: hasVariant(
              variants,
              "color",
              "softGray"
            ),

            [sty.trigger__color_softGreen]: hasVariant(
              variants,
              "color",
              "softGreen"
            ),

            [sty.trigger__color_softOrange]: hasVariant(
              variants,
              "color",
              "softOrange"
            ),

            [sty.trigger__color_softPink]: hasVariant(
              variants,
              "color",
              "softPink"
            ),

            [sty.trigger__color_softPurple]: hasVariant(
              variants,
              "color",
              "softPurple"
            ),

            [sty.trigger__color_softRed]: hasVariant(
              variants,
              "color",
              "softRed"
            ),

            [sty.trigger__color_softYellow]: hasVariant(
              variants,
              "color",
              "softYellow"
            ),

            [sty.trigger__isDisabled]: hasVariant(
              variants,
              "isDisabled",
              "isDisabled"
            ),

            [sty.trigger__isOpen]: hasVariant(variants, "isOpen", "isOpen")
          })}
          disabled={
            hasVariant(variants, "isDisabled", "isDisabled") ? true : undefined
          }
        >
          <div
            data-plasmic-name={"contentContainer"}
            data-plasmic-override={overrides.contentContainer}
            className={classNames(defaultcss.all, sty.contentContainer, {
              [sty.contentContainer__color_softBlue]: hasVariant(
                variants,
                "color",
                "softBlue"
              ),

              [sty.contentContainer__isDisabled]: hasVariant(
                variants,
                "isDisabled",
                "isDisabled"
              ),

              [sty.contentContainer__showPlaceholder]: hasVariant(
                variants,
                "showPlaceholder",
                "showPlaceholder"
              )
            })}
          >
            {(
              hasVariant(variants, "showPlaceholder", "showPlaceholder")
                ? false
                : true
            )
              ? p.renderPlasmicSlot({
                  defaultContents: "Selected",
                  value: args.selectedContent,
                  className: classNames(sty.slotTargetSelectedContent, {
                    [sty.slotTargetSelectedContent__color_softBlue]: hasVariant(
                      variants,
                      "color",
                      "softBlue"
                    ),

                    [sty.slotTargetSelectedContent__color_softCyan]: hasVariant(
                      variants,
                      "color",
                      "softCyan"
                    ),

                    [sty.slotTargetSelectedContent__color_softGreen]:
                      hasVariant(variants, "color", "softGreen"),
                    [sty.slotTargetSelectedContent__color_softOrange]:
                      hasVariant(variants, "color", "softOrange"),
                    [sty.slotTargetSelectedContent__color_softPink]: hasVariant(
                      variants,
                      "color",
                      "softPink"
                    ),

                    [sty.slotTargetSelectedContent__color_softPurple]:
                      hasVariant(variants, "color", "softPurple"),
                    [sty.slotTargetSelectedContent__color_softRed]: hasVariant(
                      variants,
                      "color",
                      "softRed"
                    ),

                    [sty.slotTargetSelectedContent__color_softYellow]:
                      hasVariant(variants, "color", "softYellow"),
                    [sty.slotTargetSelectedContent__isDisabled]: hasVariant(
                      variants,
                      "isDisabled",
                      "isDisabled"
                    ),

                    [sty.slotTargetSelectedContent__isOpen]: hasVariant(
                      variants,
                      "isOpen",
                      "isOpen"
                    ),

                    [sty.slotTargetSelectedContent__showPlaceholder]:
                      hasVariant(variants, "showPlaceholder", "showPlaceholder")
                  })
                })
              : null}
            {(
              hasVariant(variants, "showPlaceholder", "showPlaceholder")
                ? true
                : false
            )
              ? p.renderPlasmicSlot({
                  defaultContents: "Select…",
                  value: args.placeholder,
                  className: classNames(sty.slotTargetPlaceholder, {
                    [sty.slotTargetPlaceholder__color_softBlue]: hasVariant(
                      variants,
                      "color",
                      "softBlue"
                    ),

                    [sty.slotTargetPlaceholder__color_softPurple_showPlaceholder]:
                      hasVariant(variants, "color", "softPurple") &&
                      hasVariant(
                        variants,
                        "showPlaceholder",
                        "showPlaceholder"
                      ),

                    [sty.slotTargetPlaceholder__showPlaceholder]: hasVariant(
                      variants,
                      "showPlaceholder",
                      "showPlaceholder"
                    ),

                    [sty.slotTargetPlaceholder__showPlaceholder_color_softBlue]:
                      hasVariant(
                        variants,
                        "showPlaceholder",
                        "showPlaceholder"
                      ) && hasVariant(variants, "color", "softBlue"),
                    [sty.slotTargetPlaceholder__showPlaceholder_color_softCyan]:
                      hasVariant(
                        variants,
                        "showPlaceholder",
                        "showPlaceholder"
                      ) && hasVariant(variants, "color", "softCyan"),
                    [sty.slotTargetPlaceholder__showPlaceholder_color_softGreen]:
                      hasVariant(
                        variants,
                        "showPlaceholder",
                        "showPlaceholder"
                      ) && hasVariant(variants, "color", "softGreen"),
                    [sty.slotTargetPlaceholder__showPlaceholder_color_softOrange]:
                      hasVariant(
                        variants,
                        "showPlaceholder",
                        "showPlaceholder"
                      ) && hasVariant(variants, "color", "softOrange"),
                    [sty.slotTargetPlaceholder__showPlaceholder_color_softPink]:
                      hasVariant(
                        variants,
                        "showPlaceholder",
                        "showPlaceholder"
                      ) && hasVariant(variants, "color", "softPink"),
                    [sty.slotTargetPlaceholder__showPlaceholder_color_softRed]:
                      hasVariant(
                        variants,
                        "showPlaceholder",
                        "showPlaceholder"
                      ) && hasVariant(variants, "color", "softRed"),
                    [sty.slotTargetPlaceholder__showPlaceholder_color_softYellow]:
                      hasVariant(
                        variants,
                        "showPlaceholder",
                        "showPlaceholder"
                      ) && hasVariant(variants, "color", "softYellow")
                  })
                })
              : null}
          </div>

          <p.PlasmicIcon
            data-plasmic-name={"dropdownIcon"}
            data-plasmic-override={overrides.dropdownIcon}
            PlasmicIconType={
              hasVariant(variants, "isOpen", "isOpen")
                ? ChevronUpsvgIcon
                : ChevronDownsvgIcon
            }
            className={classNames(defaultcss.all, sty.dropdownIcon, {
              [sty.dropdownIcon_____focusVisibleWithin]:
                triggers.focusVisibleWithin_root,
              [sty.dropdownIcon__color_softBlue]: hasVariant(
                variants,
                "color",
                "softBlue"
              ),

              [sty.dropdownIcon__color_softCyan]: hasVariant(
                variants,
                "color",
                "softCyan"
              ),

              [sty.dropdownIcon__color_softGray]: hasVariant(
                variants,
                "color",
                "softGray"
              ),

              [sty.dropdownIcon__color_softGreen]: hasVariant(
                variants,
                "color",
                "softGreen"
              ),

              [sty.dropdownIcon__color_softOrange]: hasVariant(
                variants,
                "color",
                "softOrange"
              ),

              [sty.dropdownIcon__color_softPink]: hasVariant(
                variants,
                "color",
                "softPink"
              ),

              [sty.dropdownIcon__color_softPurple]: hasVariant(
                variants,
                "color",
                "softPurple"
              ),

              [sty.dropdownIcon__color_softRed]: hasVariant(
                variants,
                "color",
                "softRed"
              ),

              [sty.dropdownIcon__color_softYellow]: hasVariant(
                variants,
                "color",
                "softYellow"
              ),

              [sty.dropdownIcon__isDisabled]: hasVariant(
                variants,
                "isDisabled",
                "isDisabled"
              ),

              [sty.dropdownIcon__isOpen]: hasVariant(
                variants,
                "isOpen",
                "isOpen"
              )
            })}
            role={"img"}
          />
        </button>

        {(hasVariant(variants, "isOpen", "isOpen") ? true : false) ? (
          <Select__Overlay
            data-plasmic-name={"overlay"}
            data-plasmic-override={overrides.overlay}
            className={classNames("__wab_instance", sty.overlay, {
              [sty.overlay__isOpen]: hasVariant(variants, "isOpen", "isOpen")
            })}
            relativePlacement={"bottom"}
          >
            <div
              data-plasmic-name={"optionsContainer"}
              data-plasmic-override={overrides.optionsContainer}
              className={classNames(defaultcss.all, sty.optionsContainer, {
                [sty.optionsContainer__isOpen]: hasVariant(
                  variants,
                  "isOpen",
                  "isOpen"
                )
              })}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <React.Fragment>
                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__w0Qr1
                      )}
                      value={"value1"}
                    >
                      {"Option 1"}
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__gsy3Z
                      )}
                      value={"value2"}
                    >
                      {"Option 2"}
                    </Select__Option>
                  </React.Fragment>
                ),

                value: args.children
              })}
            </div>
          </Select__Overlay>
        ) : null}
      </div>
    </PlasmicSelectContext.Provider>
  );
}

function useBehavior(props, ref) {
  if (!("children" in props)) {
    props = {
      ...props,
      children: (
        <React.Fragment>
          <Select__Option
            className={classNames("__wab_instance", sty.option__w0Qr1)}
            value={"value1"}
          >
            {"Option 1"}
          </Select__Option>

          <Select__Option
            className={classNames("__wab_instance", sty.option__gsy3Z)}
            value={"value2"}
          >
            {"Option 2"}
          </Select__Option>
        </React.Fragment>
      )
    };
  }
  return pp.useSelect(
    PlasmicSelect,
    props,
    {
      isOpenVariant: { group: "isOpen", variant: "isOpen" },
      placeholderVariant: {
        group: "showPlaceholder",
        variant: "showPlaceholder"
      },

      isDisabledVariant: { group: "isDisabled", variant: "isDisabled" },
      triggerContentSlot: "selectedContent",
      optionsSlot: "children",
      placeholderSlot: "placeholder",
      root: "root",
      trigger: "trigger",
      overlay: "overlay",
      optionsContainer: "optionsContainer"
    },

    ref
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "trigger",
    "contentContainer",
    "dropdownIcon",
    "overlay",
    "optionsContainer"
  ],

  trigger: ["trigger", "contentContainer", "dropdownIcon"],
  contentContainer: ["contentContainer"],
  dropdownIcon: ["dropdownIcon"],
  overlay: ["overlay", "optionsContainer"],
  optionsContainer: ["optionsContainer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSelect__ArgProps,
      internalVariantPropNames: PlasmicSelect__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicSelect__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSelect";
  } else {
    func.displayName = `PlasmicSelect.${nodeName}`;
  }
  return func;
}

export const PlasmicSelect = Object.assign(
  // Top-level PlasmicSelect renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    trigger: makeNodeComponent("trigger"),
    contentContainer: makeNodeComponent("contentContainer"),
    dropdownIcon: makeNodeComponent("dropdownIcon"),
    overlay: makeNodeComponent("overlay"),
    optionsContainer: makeNodeComponent("optionsContainer"),
    // Metadata about props expected for PlasmicSelect
    internalVariantProps: PlasmicSelect__VariantProps,
    internalArgProps: PlasmicSelect__ArgProps,
    // Context for sub components
    Context: PlasmicSelectContext,
    useBehavior
  }
);

export default PlasmicSelect;
/* prettier-ignore-end */
